apiVersion: v1
kind: ConfigMap
metadata:
  name: hospital-config
  namespace: hospital
data:
  SPRING_MAIL_HOST: "smtp.gmail.com"
  SPRING_MAIL_PORT: "587"
  OAUTH_REDIRECT_URI: "https://hospital-management-0rx3.onrender.com/api/v1/login/oauth2/code/google"
  FRONTEND_URL: "https://hospital-management-eight-sandy.vercel.app"
  KAFKA_ENABLED: "true"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"